### PR TITLE
Feat/vim8plugins

### PR DESCRIPTION
**Pull request by claudex**
I'm not an expert in vim plugins but it works with vim 8 native plugins management.

### CODE REVIEW

**Comment by kalekundert** [comment]
Thank you, looks good!

**Comment by andymass** [comment]
The symlink plugin/coiledsnake.vim means that the plugin will be loaded and folding altered for whatever file you first open in vim, regardless of filetype.

**Comment by kalekundert** [comment]
Thanks for the catch, let me look at this more closely when I have some time later tonight.

**Comment by lervag** [comment]
You should really remove the symlink, because it ends up breaking things on my end (and I would expect for others as well). This is a filetype plugin for python, __not__ a regular Vim plugin. You can read more about the distinction e.g. in `:help 'runtimepath'`, `:help write-plugin`.

**Comment by andymass** [comment]
@lervag this is the same problem as vimtex not loading with packs right?  Starting to think this is a vim bug.

**Comment by lervag** [comment]
@andymass Not sure. My problem is not related to packs, since I don't use them.

**Comment by kalekundert** [comment]
Thanks for the prodding, and sorry this took me all week.  I wanted to read about vim8 native plugins before doing anything, but I think @andymass was right that filetype plugins just shouldn't put anything in ``plugins/``, because everything in that directory is sourced for every file type.  I just reverted that change, so hopefully this isn't causing people problems any more.

**Comment by lervag** [comment]
Thanks! And by the way, nice work with the plugin! :)

**Pull request merged**
